name: Converted Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  PATH: ${env.PATH}:/home/jenkins/.asdf/shims:/home/jenkins/.asdf/bin
jobs:
  prepare_puppet_project:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: Run Shell Command
        run: |-
          if ! command -v yq >/dev/null 2>&1
          then
          asdf plugin-add yq https://github.com/sudermanjr/asdf-yq.git || true
          asdf install yq 4.25.3
          asdf global yq 4.25.3
          fi
      - name: Run Shell Command
        run: bash ./scripts/setupgems.sh
  syntax:
    runs-on: ubuntu-latest
    needs: [prepare_puppet_project]
    timeout-minutes: 15
    steps:
      - name: Run Shell Command
        run: bundle exec rake lint
  profiles:
    runs-on: ubuntu-latest
    needs: [prepare_puppet_project]
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: Run Shell Command
        run: bundle exec parallel_rspec spec/classes/profile
  roles:
    runs-on: ubuntu-latest
    needs: [prepare_puppet_project]
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: Run Shell Command
        run: bundle exec parallel_rspec spec/classes/role
